# BÀI TẬP: E-COMMERCE DATA (ONLINE RETAIL)
**Nguồn:** kaggle.com/datasets/carrie1/ecommerce-data (541,909 dòng)

## Setup

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/databricks/Spark-The-Definitive-Guide/master/data/retail-data/all/online-retail-dataset.csv'

df = pd.read_csv(csv_path, encoding='ISO-8859-1', on_bad_lines='skip')
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/databricks/Spark-The-Definitive-Guide/master/data/retail-data/all/online-retail-dataset.csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [2]:
# TODO
print(f"Kich thuoc du lieu gom {df.shape[0]} dong va {df.shape[1]} cot")
print("Column name:", df.columns.tolist())
print("Kieu du lieu tung cot la:\n",df.dtypes)

Kich thuoc du lieu gom 541909 dong va 8 cot
Column name: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
Kieu du lieu tung cot la:
 InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

## A.2. Missing values & Duplicate data

In [3]:
# TODO
display(df.isnull())
display(df.duplicated())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
541904,False,False,False,False,False,False,False,False
541905,False,False,False,False,False,False,False,False
541906,False,False,False,False,False,False,False,False
541907,False,False,False,False,False,False,False,False
541908,False,False,False,False,False,False,False,False

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Length: 541909, dtype: bool

## A.3. Invalid values

In [4]:
# TODO
print("Số dòng có Quantity <= 0:",
      (df['Quantity'] <= 0).sum())

print("Số dòng có UnitPrice <= 0:",
      (df['UnitPrice'] <= 0).sum())

print("Số dòng thiếu CustomerID:",
      df['CustomerID'].isnull().sum())

print("\nKiểu dữ liệu InvoiceDate:")
print(df['InvoiceDate'].dtype)

print("\nSố quốc gia:")
print(df['Country'].nunique())

Số dòng có Quantity <= 0: 10624
Số dòng có UnitPrice <= 0: 2517
Số dòng thiếu CustomerID: 135080

Kiểu dữ liệu InvoiceDate:
datetime64[us]

Số quốc gia:
38

## A.4. Create a new column
Làm sạch dữ liệu (loại Quantity<=0, UnitPrice<=0), tạo cột `Sales` = Quantity * UnitPrice.

In [6]:
# TODO
df_clean = df[
    (df['Quantity'] > 0) &
    (df['UnitPrice'] > 0)
].copy()

df_clean['Sales'] = (
    df_clean['Quantity'] *
    df_clean['UnitPrice']
)

df_clean['InvoiceDate'] = pd.to_datetime(
    df_clean['InvoiceDate']
)

print("Kích thước dữ liệu sau khi làm sạch:",
      df_clean.shape)

print("\n5 dòng đầu:")
print(df_clean.head())

Kích thước dữ liệu sau khi làm sạch: (530104, 9)

5 dòng đầu:
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country  Sales
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  22.00
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [7]:
# TODO
numeric_cols = [
    'Quantity',
    'UnitPrice',
    'Sales'
]

print("MEAN:")
print(df_clean[numeric_cols].mean())

print("\nMEDIAN:")
print(df_clean[numeric_cols].median())

print("\nMODE:")
print(df_clean[numeric_cols].mode().iloc[0])

MEAN:
Quantity     10.542037
UnitPrice     3.907625
Sales        20.121871
dtype: float64

MEDIAN:
Quantity     3.00
UnitPrice    2.08
Sales        9.90
dtype: float64

MODE:
Quantity      1.00
UnitPrice     1.25
Sales        15.00
Name: 0, dtype: float64

## Group 2 — Dispersion

In [8]:

print("VARIANCE:")
print(df_clean[numeric_cols].var())


print("\nSTANDARD DEVIATION:")
print(df_clean[numeric_cols].std())

# Minimum
print("\nMINIMUM:")
print(df_clean[numeric_cols].min())


print("\nMAXIMUM:")
print(df_clean[numeric_cols].max())

print("\nRANGE:")
print(
    df_clean[numeric_cols].max()
    - df_clean[numeric_cols].min()
)

VARIANCE:
Quantity     24187.752994
UnitPrice     1289.936149
Sales        73092.768604
dtype: float64

STANDARD DEVIATION:
Quantity     155.524124
UnitPrice     35.915681
Sales        270.356743
dtype: float64

MINIMUM:
Quantity     1.000
UnitPrice    0.001
Sales        0.001
dtype: float64

MAXIMUM:
Quantity      80995.00
UnitPrice     13541.33
Sales        168469.60
dtype: float64

RANGE:
Quantity      80994.000
UnitPrice     13541.329
Sales        168469.599
dtype: float64

## Group 3 — Location and Shape

In [9]:
# TODO
print("QUARTILES:")
print(
    df_clean[numeric_cols].quantile(
        [0.25, 0.5, 0.75]
    )
)

Q1 = df_clean[numeric_cols].quantile(0.25)
Q3 = df_clean[numeric_cols].quantile(0.75)

IQR = Q3 - Q1

print("\nIQR:")
print(IQR)

print("\nSKEWNESS:")
print(df_clean[numeric_cols].skew())

print("\nKURTOSIS:")
print(df_clean[numeric_cols].kurt())

QUARTILES:
      Quantity  UnitPrice  Sales
0.25       1.0       1.25   3.75
0.50       3.0       2.08   9.90
0.75      10.0       4.13  17.70

IQR:
Quantity      9.00
UnitPrice     2.88
Sales        13.95
dtype: float64

SKEWNESS:
Quantity     471.727716
UnitPrice    206.087555
Sales        506.706012
dtype: float64

KURTOSIS:
Quantity     236462.342826
UnitPrice     62483.142715
Sales        297651.661046
dtype: float64

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Quốc gia nào đóng góp doanh thu cao nhất, chiếm bao nhiêu % tổng doanh thu?

In [10]:
# TODO
country_sales = (
    df_clean
    .groupby('Country')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print("Doanh thu theo quốc gia:")
print(country_sales)

top_country = country_sales.idxmax()
top_sales = country_sales.max()

total_sales = df_clean['Sales'].sum()

percentage = top_sales / total_sales * 100

print("\nQuốc gia có doanh thu cao nhất:", top_country)
print(f"Doanh thu: {top_sales:,.2f}")
print(f"Tỷ lệ đóng góp: {percentage:.2f}%")

Doanh thu theo quốc gia:
Country
United Kingdom          9025222.084
Netherlands              285446.340
EIRE                     283453.960
Germany                  228867.140
France                   209715.110
Australia                138521.310
Spain                     61577.110
Switzerland               57089.900
Belgium                   41196.340
Sweden                    38378.330
Japan                     37416.370
Norway                    36165.440
Portugal                  33747.100
Finland                   22546.080
Singapore                 21279.290
Channel Islands           20450.440
Denmark                   18955.340
Italy                     17483.240
Hong Kong                 15691.800
Cyprus                    13590.380
Austria                   10198.680
Israel                     8135.260
Poland                     7334.650
Greece                     4760.520
Unspecified                4749.790
Iceland                    4310.000
Canada                     3666.380
USA                        3580.390
Malta                      2725.590
United Arab Emirates       1902.280
Lebanon                    1693.880
Lithuania                  1661.060
European Community         1300.250
Brazil                     1143.600
RSA                        1002.310
Czech Republic              826.740
Bahrain                     754.140
Saudi Arabia                145.920
Name: Sales, dtype: float64

Quốc gia có doanh thu cao nhất: United Kingdom
Doanh thu: 9,025,222.08
Tỷ lệ đóng góp: 84.61%

## Câu hỏi 2: Sản phẩm nào bán chạy nhất theo doanh thu?

In [12]:
# TODO
product_sales = (
    df_clean
    .groupby(['StockCode', 'Description'])['Sales']
    .sum()
    .sort_values(ascending=False)
)

print("Top 10 sản phẩm theo doanh thu:")
print(product_sales.head(10))

top_product = product_sales.idxmax()
top_product_sales = product_sales.max()

print("\nSản phẩm có doanh thu cao nhất:")
print("StockCode:", top_product[0])
print("Description:", top_product[1])
print(f"Doanh thu: {top_product_sales:,.2f}")

Top 10 sản phẩm theo doanh thu:
StockCode  Description
DOT        DOTCOM POSTAGE                        206248.77
22423      REGENCY CAKESTAND 3 TIER              174484.74
23843      PAPER CRAFT , LITTLE BIRDIE           168469.60
85123A     WHITE HANGING HEART T-LIGHT HOLDER    104340.29
47566      PARTY BUNTING                          99504.33
85099B     JUMBO BAG RED RETROSPOT                94340.05
23166      MEDIUM CERAMIC TOP STORAGE JAR         81700.92
M          Manual                                 78110.27
POST       POSTAGE                                78101.88
23084      RABBIT NIGHT LIGHT                     66964.99
Name: Sales, dtype: float64

Sản phẩm có doanh thu cao nhất:
StockCode: DOT
Description: DOTCOM POSTAGE
Doanh thu: 206,248.77

## Câu hỏi 3: Doanh số có tính mùa vụ theo tháng không?

In [13]:
# TODO
df_clean['Month'] = (
    df_clean['InvoiceDate']
    .dt.to_period('M')
)

monthly_sales = (
    df_clean
    .groupby('Month')['Sales']
    .sum()
)

print("Doanh thu theo tháng:")
print(monthly_sales)

Doanh thu theo tháng:
Month
2010-12     823746.140
2011-01     691364.560
2011-02     523631.890
2011-03     717639.360
2011-04     537808.621
2011-05     770536.020
2011-06     761739.900
2011-07     719221.191
2011-08     759138.380
2011-09    1058590.172
2011-10    1154979.300
2011-11    1509496.330
2011-12     638792.680
Freq: M, Name: Sales, dtype: float64

## Câu hỏi 4: Giá trị đơn hàng trung bình (Average Order Value) khác nhau thế nào giữa các quốc gia?

In [14]:
# TODO
country_aov = (
    df_clean
    .groupby('Country')
    .agg(
        Total_Sales=('Sales', 'sum'),
        Number_of_Orders=('InvoiceNo', 'nunique')
    )
)

country_aov['AOV'] = (
    country_aov['Total_Sales'] /
    country_aov['Number_of_Orders']
)

country_aov = country_aov.sort_values(
    'AOV',
    ascending=False
)

print("AOV theo quốc gia:")
print(country_aov)

AOV theo quốc gia:
                      Total_Sales  Number_of_Orders          AOV
Country
Singapore               21279.290                 7  3039.898571
Netherlands            285446.340                94  3036.663191
Australia              138521.310                57  2430.198421
Japan                   37416.370                19  1969.282632
Lebanon                  1693.880                 1  1693.880000
Hong Kong               15691.800                11  1426.527273
Brazil                   1143.600                 1  1143.600000
Sweden                  38378.330                36  1066.064722
Switzerland             57089.900                54  1057.220370
Denmark                 18955.340                18  1053.074444
Israel                   8135.260                 8  1016.907500
Norway                  36165.440                36  1004.595556
RSA                      1002.310                 1  1002.310000
EIRE                   283453.960               288   984.215139
Greece                   4760.520                 5   952.104000
Cyprus                  13590.380                16   849.398750
Channel Islands         20450.440                26   786.555385
USA                      3580.390                 5   716.078000
Spain                   61577.110                90   684.190111
United Arab Emirates     1902.280                 3   634.093333
Iceland                  4310.000                 7   615.714286
Canada                   3666.380                 6   611.063333
Austria                 10198.680                17   599.922353
Portugal                33747.100                58   581.846552
Finland                 22546.080                41   549.904390
Malta                    2725.590                 5   545.118000
France                 209715.110               392   534.987526
United Kingdom        9025222.084             18019   500.872528
Germany                228867.140               457   500.803370
Italy                   17483.240                38   460.085263
Belgium                 41196.340                98   420.370816
Lithuania                1661.060                 4   415.265000
Czech Republic            826.740                 2   413.370000
Poland                   7334.650                19   386.034211
Unspecified              4749.790                13   365.368462
European Community       1300.250                 4   325.062500
Bahrain                   754.140                 3   251.380000
Saudi Arabia              145.920                 1   145.920000

## Câu hỏi 5: Tỷ lệ giao dịch có dấu hiệu trả hàng/hủy (Quantity âm ở dữ liệu gốc) khác nhau thế nào giữa các quốc gia?

In [15]:
# TODO
df['Is_Return'] = df['Quantity'] < 0

country_transactions = (
    df.groupby('Country')
    .size()
)

country_returns = (
    df[df['Is_Return']]
    .groupby('Country')
    .size()
)

return_rate = (
    country_returns
    .reindex(country_transactions.index, fill_value=0)
    / country_transactions
    * 100
)

return_rate = return_rate.sort_values(
    ascending=False
)

print("Tỷ lệ giao dịch có Quantity âm theo quốc gia:")
print(return_rate)

Tỷ lệ giao dịch có Quantity âm theo quốc gia:
Country
USA                     38.487973
Czech Republic          16.666667
Malta                   11.811024
Japan                   10.335196
Saudi Arabia            10.000000
Australia                5.877681
Italy                    5.603985
Bahrain                  5.263158
Germany                  4.770932
EIRE                     3.684724
Poland                   3.225806
Singapore                3.056769
Sweden                   2.380952
Denmark                  2.313625
Spain                    1.894986
United Kingdom           1.855178
Belgium                  1.836636
Switzerland              1.748252
France                   1.741264
European Community       1.639344
Finland                  1.438849
Hong Kong                1.388889
Channel Islands          1.319261
Norway                   1.289134
Cyprus                   1.286174
Portugal                 1.184990
Austria                  0.748130
Greece                   0.684932
Israel                   0.673401
Netherlands              0.337410
Canada                   0.000000
Brazil                   0.000000
Lebanon                  0.000000
Iceland                  0.000000
RSA                      0.000000
Lithuania                0.000000
United Arab Emirates     0.000000
Unspecified              0.000000
dtype: float64

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể.

*(Viết insight của bạn vào đây...)*