# BÀI TẬP: TITANIC
**Nguồn:** kaggle.com/c/titanic (891 dòng)

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [2]:
# TODO
print(f"Kich thuoc du lieu gom {df.shape[0]} dong va {df.shape[1]} cot")
print("Column name:", df.columns.tolist())
print("Kieu du lieu tung cot la:\n",df.dtypes)

Kich thuoc du lieu gom 891 dong va 15 cot
Column name: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']
Kieu du lieu tung cot la:
 survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object

## A.2. Missing values & Duplicate data

In [3]:
# TODO
display(df.isnull())
display(df.duplicated())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

## A.3. Invalid values

In [4]:
# TODO
print("Giá trị Survived:")
print(df['survived'].unique())

print("\nGiá trị Pclass:")
print(df['pclass'].unique())

print("\nSố người có Age <= 0:")
print((df['age'] <= 0).sum())

print("\nSố người có Fare < 0:")
print((df['fare'] < 0).sum())

print("\nSố người có SibSp < 0:")
print((df['sibsp'] < 0).sum())

print("\nSố người có Parch < 0:")
print((df['parch'] < 0).sum())

print("\nGiá trị Sex:")
print(df['sex'].unique())

print("\nGiá trị Embark Town:")
print(df['embark_town'].unique())

Giá trị Survived:
[0 1]

Giá trị Pclass:
[3 1 2]

Số người có Age <= 0:
0

Số người có Fare < 0:
0

Số người có SibSp < 0:
0

Số người có Parch < 0:
0

Giá trị Sex:
<StringArray>
['male', 'female']
Length: 2, dtype: str

Giá trị Embark Town:
<StringArray>
['Southampton', 'Cherbourg', 'Queenstown', nan]
Length: 4, dtype: str

## A.4. Create a new column
Tạo cột `family_size` = sibsp + parch + 1.

In [5]:
# TODO
df['family_size'] = (
    df['sibsp'] +
    df['parch'] +
    1
)

print(df[['sibsp', 'parch', 'family_size']].head(10))

   sibsp  parch  family_size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1
5      0      0            1
6      0      0            1
7      3      1            5
8      0      2            3
9      1      0            2

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [6]:
# TODO
numeric_cols = [
    'age',
    'fare',
    'sibsp',
    'parch',
    'family_size'
]

print("MEAN:")
print(df[numeric_cols].mean())

print("\nMEDIAN:")
print(df[numeric_cols].median())

print("\nMODE:")
print(df[numeric_cols].mode().iloc[0])

MEAN:
age            29.699118
fare           32.204208
sibsp           0.523008
parch           0.381594
family_size     1.904602
dtype: float64

MEDIAN:
age            28.0000
fare           14.4542
sibsp           0.0000
parch           0.0000
family_size     1.0000
dtype: float64

MODE:
age            24.00
fare            8.05
sibsp           0.00
parch           0.00
family_size     1.00
Name: 0, dtype: float64

## Group 2 — Dispersion

In [7]:
# TODO
print("VARIANCE:")
print(df[numeric_cols].var())

print("\nSTANDARD DEVIATION:")
print(df[numeric_cols].std())

print("\nMINIMUM:")
print(df[numeric_cols].min())

print("\nMAXIMUM:")
print(df[numeric_cols].max())

print("\nRANGE:")
print(
    df[numeric_cols].max()
    - df[numeric_cols].min()
)

VARIANCE:
age             211.019125
fare           2469.436846
sibsp             1.216043
parch             0.649728
family_size       2.603248
dtype: float64

STANDARD DEVIATION:
age            14.526497
fare           49.693429
sibsp           1.102743
parch           0.806057
family_size     1.613459
dtype: float64

MINIMUM:
age            0.42
fare           0.00
sibsp          0.00
parch          0.00
family_size    1.00
dtype: float64

MAXIMUM:
age             80.0000
fare           512.3292
sibsp            8.0000
parch            6.0000
family_size     11.0000
dtype: float64

RANGE:
age             79.5800
fare           512.3292
sibsp            8.0000
parch            6.0000
family_size     10.0000
dtype: float64

## Group 3 — Location and Shape

In [8]:

print("QUARTILES:")
print(
    df[numeric_cols].quantile(
        [0.25, 0.5, 0.75]
    )
)

Q1 = df[numeric_cols].quantile(0.25)

Q3 = df[numeric_cols].quantile(0.75)

IQR = Q3 - Q1

print("\nIQR:")
print(IQR)

print("\nSKEWNESS:")
print(df[numeric_cols].skew())

print("\nKURTOSIS:")
print(df[numeric_cols].kurt())

QUARTILES:
         age     fare  sibsp  parch  family_size
0.25  20.125   7.9104    0.0    0.0          1.0
0.50  28.000  14.4542    0.0    0.0          1.0
0.75  38.000  31.0000    1.0    0.0          2.0

IQR:
age            17.8750
fare           23.0896
sibsp           1.0000
parch           0.0000
family_size     1.0000
dtype: float64

SKEWNESS:
age            0.389108
fare           4.787317
sibsp          3.695352
parch          2.749117
family_size    2.727441
dtype: float64

KURTOSIS:
age             0.178274
fare           33.398141
sibsp          17.880420
parch           9.778125
family_size     9.159666
dtype: float64

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Hạng vé nào có tỷ lệ sống sót cao nhất, chênh lệch bao nhiêu so với hạng thấp nhất?

In [9]:
# TODO
survival_by_class = (
    df.groupby('pclass')['survived']
    .mean()
    .sort_values(ascending=False)
)

print("Tỷ lệ sống sót theo hạng vé:")
print(survival_by_class)

highest_class = survival_by_class.idxmax()
highest_rate = survival_by_class.max()

lowest_class = survival_by_class.idxmin()
lowest_rate = survival_by_class.min()

difference = highest_rate - lowest_rate

print(
    f"\nHạng vé có tỷ lệ sống sót cao nhất: "
    f"{highest_class}"
)

print(
    f"Tỷ lệ sống sót cao nhất: "
    f"{highest_rate * 100:.2f}%"
)

print(
    f"Hạng có tỷ lệ thấp nhất: "
    f"{lowest_class}"
)

print(
    f"Tỷ lệ sống sót thấp nhất: "
    f"{lowest_rate * 100:.2f}%"
)

print(
    f"Chênh lệch: "
    f"{difference * 100:.2f} điểm phần trăm"
)

Tỷ lệ sống sót theo hạng vé:
pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

Hạng vé có tỷ lệ sống sót cao nhất: 1
Tỷ lệ sống sót cao nhất: 62.96%
Hạng có tỷ lệ thấp nhất: 3
Tỷ lệ sống sót thấp nhất: 24.24%
Chênh lệch: 38.73 điểm phần trăm

## Câu hỏi 2: Giới tính hay hạng vé ảnh hưởng đến sống sót mạnh hơn?

In [11]:
# TODO
survival_by_sex = (
    df.groupby('sex')['survived']
    .mean()
)

print("Tỷ lệ sống sót theo giới tính:")
print(survival_by_sex)

sex_difference = (
    survival_by_sex.max()
    - survival_by_sex.min()
)

print(
    "\nChênh lệch theo giới tính:",
    round(sex_difference * 100, 2),
    "điểm phần trăm"
)

Tỷ lệ sống sót theo giới tính:
sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

Chênh lệch theo giới tính: 55.31 điểm phần trăm

## Câu hỏi 3: Vé đắt hơn có thực sự sống sót cao hơn không?

In [12]:
# TODO
survival_by_class = (
    df.groupby('pclass')['survived']
    .mean()
)

class_difference = (
    survival_by_class.max()
    - survival_by_class.min()
)

print(
    "Chênh lệch theo hạng vé:",
    round(class_difference * 100, 2),
    "điểm phần trăm"
)

Chênh lệch theo hạng vé: 38.73 điểm phần trăm

## Câu hỏi 4: Gia đình đông người có ảnh hưởng đến khả năng sống sót không?

In [14]:
# TODO
if sex_difference > class_difference:
    print(
        "\n=> Giới tính có ảnh hưởng mạnh hơn "
        "đến tỷ lệ sống sót."
    )
else:
    print(
        "\n=> Hạng vé có ảnh hưởng mạnh hơn "
        "đến tỷ lệ sống sót."
    )
corr_family_survived = (
    df['family_size']
    .corr(df['survived'])
)

print(
    "Hệ số tương quan Family Size - Survived:",
    round(corr_family_survived, 4)
)

=> Giới tính có ảnh hưởng mạnh hơn đến tỷ lệ sống sót.
Hệ số tương quan Family Size - Survived: 0.0166

## Câu hỏi 5: Cảng lên tàu (embark_town) nào có tỷ lệ sống sót cao nhất?

In [15]:
# TODO
survival_by_port = (
    df.groupby('embark_town')['survived']
    .mean()
    .sort_values(ascending=False)
)

print(
    "Tỷ lệ sống sót theo cảng lên tàu:"
)

print(survival_by_port)

best_port = survival_by_port.idxmax()
best_port_rate = survival_by_port.max()

print(
    f"\nCảng có tỷ lệ sống sót cao nhất: "
    f"{best_port}"
)

print(
    f"Tỷ lệ sống sót: "
    f"{best_port_rate * 100:.2f}%"
)

Tỷ lệ sống sót theo cảng lên tàu:
embark_town
Cherbourg      0.553571
Queenstown     0.389610
Southampton    0.336957
Name: survived, dtype: float64

Cảng có tỷ lệ sống sót cao nhất: Cherbourg
Tỷ lệ sống sót: 55.36%

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể về dữ liệu Titanic.

*(Viết insight của bạn vào đây...)*